heat_template_version: 2018-08-31

description: >
  This HOT template to create below items.
  Create a Instance with floating IP
  Created By
  Vinothkumar P

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to Instance
    default: demo-keypair

  image:
    type: string
    description: Name of image to use for Instance
    default: cirros

  server_flavor:
    type: string
    description: Flavor to use for Instance
    default: m1.small

  server_hostname:
    type: string
    description: Instance Hostname
    default: vm-01

  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: provider

  private_net_name:
    type: string
    description: Name of private network
    default: Private-Network-01

  private_subnet_name:
    type: string
    description: Name of private network
    default: Private-Subnet-Network-01


resources:
  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_hostname }
      image: { get_param: image }
      flavor: { get_param: server_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: instance_port }

  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_name }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_name }

  instance_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: instance_port }

outputs:
  instance_public_ip:
    description: IP address of Instance in public network and hostname
    value: 
      server:
        name: { get_param: server_hostname }
        address: { get_attr: [ instance_floating_ip, floating_ip_address ] }
